name: build bushi
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: build docker
        run: docker build docker -t bushi:latest
      - name: build pdf
        run: docker run --mount type=bind,source="$(pwd)",target=/workdir bushi:latest
      - name: save artifact
        uses: actions/upload-artifact@v2
        with:
          name: bushi.pdf
          path: out/bushi.pdf
