name: build bushi
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: build pdf
        run: make docker BUILD_IMAGE_TAG=1.4.0-git
      - name: save log
        uses: actions/upload-artifact@v3
        with:
          name: log
          path: out/*.log
      - name: save artifact
        uses: actions/upload-artifact@v3
        with:
          name: bushi.pdf
          path: out/bushi.pdf
          if-no-files-found: error
