name: build and push bushi build image
on:
  push:
    tags:
      - 'image/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get tag
        id: variables
        run: echo "::set-output name=tag::${GITHUB_REF##*/}"
      - name: Check out the repo
        uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          context: docker
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/bushi-build-image:latest
            ghcr.io/${{ github.repository_owner }}/bushi-build-image:${{ steps.variables.outputs.tag }}
